name: flutter_wyz
description: A new Flutter application.

version: 1.1.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_permissions: 0.1.9
  package_info: 0.3.2+1
  path_provider: ^1.4.0
  flutter_downloader: ^1.4.3
  open_file: 3.0.1
  image_picker: ^0.6.7
  image_crop: ^0.3.2
  shared_preferences: 0.4.0
  flutter_image_compress: ^0.6.8
  cupertino_icons: ^0.1.2
  http: ^0.12.0
  barcode_scan: ^1.0.0
  cached_network_image: 2.2.0+1
  exifdart: ^0.7.0+3
  dio: ^2.0.0
  jpush_flutter: 0.5.5
  flutter_sound: ^4.0.6
  wifi: 0.1.5
  flutter_drag_scale:
    git: https://github.com/LiuC520/flutter_drag_scale.git
  #  android only 如果在苹果手机或者苹果虚拟机上运行，请注释掉local_notifications
  #  local_notifications: 0.0.3
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

#dependency_overrides:
#  intl: ^0.16.1

flutter:
  uses-material-design: true
  assets:
  - img/start.jpg
  - img/loading.gif
  - img/p.jpg
  - img/p.png
  - img/pp.png
  - img/add.png
  - img/love.png
  - img/chat.png
  - img/back.png
  - img/ic_mic.png
  - img/ic_pause.png
  - img/ic_play.png
  - img/ic_stop.png
  - img/ic_volume_down.png
  - img/ic_volume_up.png
  - img/luyin.gif
  - img/luyin.png
  - img/yyr.png
  - img/yyl.png
  - img/ld.gif
  - img/on.png
  - img/off.png
  - img/lx.png
  - img/wd.png
  - img/sd.png